# all available options: https://goreleaser.com/customization/
version: 2

project_name: summon

before:
  hooks:
  - go mod download

builds:
- id: summon
  binary: summon
  env:
  - CGO_ENABLED=0
  flags:
  - -tags=netgo
  goos:
  - darwin  # MacOS
  - solaris
  - windows
  goarch:
  - amd64
  ldflags:
    - -s -w
    - -X "github.com/cyberark/summon/pkg/summon.Tag={{ .ShortCommit }}"
    - -X "github.com/cyberark/summon/pkg/summon.Version={{ .Env.VERSION }}"
  main: ./cmd/main.go
  hooks:
    post:
      # Copy the binary out into the <dist> path, and give the copy the name we want
      # in the release <extra_files>.
      # e.g. Suppose a windows amd64 build generates a binary at
      # path/to/binary.exe. This will be copied to
      # path/to/../binary-windows_amd64.exe. The copy path can then be added to
      # the release <extra_files> and will result in a release artifact with the name
      # binary-windows_amd64.exe.
      - mkdir -p "{{ dir .Path }}/../binaries"
      - cp "{{ .Path }}" "{{ dir .Path }}/../binaries/summon_{{ .Target }}{{ .Ext }}"

# Arm support
- id: summon-arm
  binary: summon
  env:
  - CGO_ENABLED=0
  flags:
  - -tags=netgo
  goos:
  - darwin  # MacOS
  - linux
  goarch:
  - arm64
  ldflags:
    - -s -w
    - -X "github.com/cyberark/summon/pkg/summon.Tag={{ .ShortCommit }}"
    - -X "github.com/cyberark/summon/pkg/summon.Version={{ .Env.VERSION }}"
  main: ./cmd/main.go
  hooks:
    post:
      # Copy the binary out into the <dist> path, and give the copy the name we want
      # in the release <extra_files>.
      # e.g. Suppose a windows amd64 build generates a binary at
      # path/to/binary.exe. This will be copied to
      # path/to/../binary-windows_amd64.exe. The copy path can then be added to
      # the release <extra_files> and will result in a release artifact with the name
      # binary-windows_amd64.exe.
      - mkdir -p "{{ dir .Path }}/../binaries"
      - cp "{{ .Path }}" "{{ dir .Path }}/../binaries/summon_{{ .Target }}{{ .Ext }}"

# Make a static build for Linux
- id: summon-linux
  binary: summon
  env:
  - CGO_ENABLED=1
  flags:
  - -tags=netgo
  goos:
  - linux
  goarch:
  - amd64
  ldflags:
    - -s -w
    - -X "github.com/cyberark/summon/pkg/summon.Tag={{ .ShortCommit }}"
    - -X "github.com/cyberark/summon/pkg/summon.Version={{ .Env.VERSION }}"
    - -linkmode external -extldflags "-static"
  main: ./cmd/main.go
  hooks:
    post:
      # Copy the binary out into the <dist> path, and give the copy the name we want
      # in the release <extra_files>.
      # e.g. Suppose a windows amd64 build generates a binary at
      # path/to/binary.exe. This will be copied to
      # path/to/../binary-windows_amd64.exe. The copy path can then be added to
      # the release <extra_files> and will result in a release artifact with the name
      # binary-windows_amd64.exe.
      - mkdir -p "{{ dir .Path }}/../binaries"
      - cp "{{ .Path }}" "{{ dir .Path }}/../binaries/summon-{{ .Target }}{{ .Ext }}"


archives:
  - id: summon-release-archive
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"
    format_overrides:
    - goos: windows
      format: zip
    files:
      - none*  # only package the binary - not defaults: readme, license, changelog

checksum:
  name_template: 'SHA256SUMS.txt'

brews:
  - description: CLI that provides on-demand secrets access for common DevOps tools.
    homepage: https://github.com/cyberark/summon
    url_template: https://github.com/cyberark/summon/releases/download/v{{.Version}}/summon-{{ tolower .Os }}-{{ tolower .Arch }}.tar.gz
    install: |
      bin.install "summon"
    test: |
      system "#{bin}/summon", "-v"

    repository:
      owner: cyberark
      name: homebrew-tools
    skip_upload: true

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    vendor: CyberArk
    homepage: https://github.com/cyberark/summon
    maintainer: Conjur Maintainers <conj_maintainers@cyberark.com>

    description: CLI that provides on-demand secrets access for common DevOps tools.
    recommends:
      - summon-conjur
    license: MIT
    formats:
    - deb
    - rpm
    - apk
    bindir: /usr/local/bin

dist: ./dist/goreleaser

release:
  disable: true
  draft: true
  extra_files:
    - glob: LICENSE
    - glob: CHANGELOG.md
