version: '2'
services:
  # summon:
  summon-builder:
    build: .
    image: summon-builder
    volumes:
      - ./output:/go/src/github.com/cyberark/summon/output
    environment:
      GOOS:
      GOARCH:

  ubuntu-16.04:
    image: ubuntu:16.04
    volumes:
      - ./install.sh:/tmp/install.sh

  ubuntu-14.04:
    image: ubuntu:14.04
    volumes:
      - ./install.sh:/tmp/install.sh
