version: 2.0

jobs:
  build:
    steps:
      - checkout
      # Build
      - run: ./build.sh

  test:
    steps:
      - run:
          name: Unit tests
          command: ./test.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
