version: 2.0

jobs:
  build:
    machine: true
    steps:
      - checkout
      # Build
      - run: ./build.sh
      
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: .

  test:
    machine: true
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: .
      - run:
          name: Unit tests
          command: ./test.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
